version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "go-grpc-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6001
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "go-grpc-service"
    environment:
      TEST: "test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "6001"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge