// Code generated by protoc-gen-go. DO NOT EDIT
// source: rocket/v1/rocket.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: rocket/v1/rocket.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rocket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Rocket) Reset() {
	*x = Rocket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rocket) ProtoMessage() {}

func (x *Rocket) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rocket.ProtoReflect.Descriptor instead.
func (*Rocket) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{0}
}

func (x *Rocket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rocket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rocket) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetRocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRocketRequest) Reset() {
	*x = GetRocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketRequest) ProtoMessage() {}

func (x *GetRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketRequest.ProtoReflect.Descriptor instead.
func (*GetRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{1}
}

func (x *GetRocketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRocketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *GetRocketResponse) Reset() {
	*x = GetRocketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketResponse) ProtoMessage() {}

func (x *GetRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketResponse.ProtoReflect.Descriptor instead.
func (*GetRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{2}
}

func (x *GetRocketResponse) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type AddRocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *AddRocketRequest) Reset() {
	*x = AddRocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRocketRequest) ProtoMessage() {}

func (x *AddRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRocketRequest.ProtoReflect.Descriptor instead.
func (*AddRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{3}
}

func (x *AddRocketRequest) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type AddRocketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *AddRocketResponse) Reset() {
	*x = AddRocketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRocketResponse) ProtoMessage() {}

func (x *AddRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRocketResponse.ProtoReflect.Descriptor instead.
func (*AddRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{4}
}

func (x *AddRocketResponse) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type DeleteRocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *DeleteRocketRequest) Reset() {
	*x = DeleteRocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRocketRequest) ProtoMessage() {}

func (x *DeleteRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRocketRequest.ProtoReflect.Descriptor instead.
func (*DeleteRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRocketRequest) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type DeleteRocketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteRocketResponse) Reset() {
	*x = DeleteRocketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rocket_v1_rocket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRocketResponse) ProtoMessage() {}

func (x *DeleteRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_v1_rocket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRocketResponse.ProtoReflect.Descriptor instead.
func (*DeleteRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_v1_rocket_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRocketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rocket_v1_rocket_proto protoreflect.FileDescriptor

var file_rocket_v1_rocket_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x40, 0x0a, 0x06, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x22, 0x3a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22,
	0x3b, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x3d, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xde, 0x01, 0x0a, 0x0d,
	0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x72, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x72,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1b, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09,
	0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rocket_v1_rocket_proto_rawDescOnce sync.Once
	file_rocket_v1_rocket_proto_rawDescData = file_rocket_v1_rocket_proto_rawDesc
)

func file_rocket_v1_rocket_proto_rawDescGZIP() []byte {
	file_rocket_v1_rocket_proto_rawDescOnce.Do(func() {
		file_rocket_v1_rocket_proto_rawDescData = protoimpl.X.CompressGZIP(file_rocket_v1_rocket_proto_rawDescData)
	})
	return file_rocket_v1_rocket_proto_rawDescData
}

var file_rocket_v1_rocket_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rocket_v1_rocket_proto_goTypes = []interface{}{
	(*Rocket)(nil),               // 0: rocket.Rocket
	(*GetRocketRequest)(nil),     // 1: rocket.GetRocketRequest
	(*GetRocketResponse)(nil),    // 2: rocket.GetRocketResponse
	(*AddRocketRequest)(nil),     // 3: rocket.AddRocketRequest
	(*AddRocketResponse)(nil),    // 4: rocket.AddRocketResponse
	(*DeleteRocketRequest)(nil),  // 5: rocket.DeleteRocketRequest
	(*DeleteRocketResponse)(nil), // 6: rocket.DeleteRocketResponse
}
var file_rocket_v1_rocket_proto_depIdxs = []int32{
	0, // 0: rocket.GetRocketResponse.rocket:type_name -> rocket.Rocket
	0, // 1: rocket.AddRocketRequest.rocket:type_name -> rocket.Rocket
	0, // 2: rocket.AddRocketResponse.rocket:type_name -> rocket.Rocket
	0, // 3: rocket.DeleteRocketRequest.rocket:type_name -> rocket.Rocket
	1, // 4: rocket.RocketService.GetRocket:input_type -> rocket.GetRocketRequest
	3, // 5: rocket.RocketService.AddRocket:input_type -> rocket.AddRocketRequest
	5, // 6: rocket.RocketService.DeleteRocket:input_type -> rocket.DeleteRocketRequest
	2, // 7: rocket.RocketService.GetRocket:output_type -> rocket.GetRocketResponse
	4, // 8: rocket.RocketService.AddRocket:output_type -> rocket.AddRocketResponse
	6, // 9: rocket.RocketService.DeleteRocket:output_type -> rocket.DeleteRocketResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rocket_v1_rocket_proto_init() }
func file_rocket_v1_rocket_proto_init() {
	if File_rocket_v1_rocket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rocket_v1_rocket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rocket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRocketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRocketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rocket_v1_rocket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRocketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rocket_v1_rocket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rocket_v1_rocket_proto_goTypes,
		DependencyIndexes: file_rocket_v1_rocket_proto_depIdxs,
		MessageInfos:      file_rocket_v1_rocket_proto_msgTypes,
	}.Build()
	File_rocket_v1_rocket_proto = out.File
	file_rocket_v1_rocket_proto_rawDesc = nil
	file_rocket_v1_rocket_proto_goTypes = nil
	file_rocket_v1_rocket_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RocketServiceClient is the client API for RocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RocketServiceClient interface {
	GetRocket(ctx context.Context, in *GetRocketRequest, opts ...grpc.CallOption) (*GetRocketResponse, error)
	AddRocket(ctx context.Context, in *AddRocketRequest, opts ...grpc.CallOption) (*AddRocketResponse, error)
	DeleteRocket(ctx context.Context, in *DeleteRocketRequest, opts ...grpc.CallOption) (*DeleteRocketResponse, error)
}

type rocketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRocketServiceClient(cc grpc.ClientConnInterface) RocketServiceClient {
	return &rocketServiceClient{cc}
}

func (c *rocketServiceClient) GetRocket(ctx context.Context, in *GetRocketRequest, opts ...grpc.CallOption) (*GetRocketResponse, error) {
	out := new(GetRocketResponse)
	err := c.cc.Invoke(ctx, "/rocket.RocketService/GetRocket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocketServiceClient) AddRocket(ctx context.Context, in *AddRocketRequest, opts ...grpc.CallOption) (*AddRocketResponse, error) {
	out := new(AddRocketResponse)
	err := c.cc.Invoke(ctx, "/rocket.RocketService/AddRocket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocketServiceClient) DeleteRocket(ctx context.Context, in *DeleteRocketRequest, opts ...grpc.CallOption) (*DeleteRocketResponse, error) {
	out := new(DeleteRocketResponse)
	err := c.cc.Invoke(ctx, "/rocket.RocketService/DeleteRocket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RocketServiceServer is the server API for RocketService service.
type RocketServiceServer interface {
	GetRocket(context.Context, *GetRocketRequest) (*GetRocketResponse, error)
	AddRocket(context.Context, *AddRocketRequest) (*AddRocketResponse, error)
	DeleteRocket(context.Context, *DeleteRocketRequest) (*DeleteRocketResponse, error)
}

// UnimplementedRocketServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRocketServiceServer struct {
}

func (*UnimplementedRocketServiceServer) GetRocket(context.Context, *GetRocketRequest) (*GetRocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRocket not implemented")
}
func (*UnimplementedRocketServiceServer) AddRocket(context.Context, *AddRocketRequest) (*AddRocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRocket not implemented")
}
func (*UnimplementedRocketServiceServer) DeleteRocket(context.Context, *DeleteRocketRequest) (*DeleteRocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRocket not implemented")
}

func RegisterRocketServiceServer(s *grpc.Server, srv RocketServiceServer) {
	s.RegisterService(&_RocketService_serviceDesc, srv)
}

func _RocketService_GetRocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocketServiceServer).GetRocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rocket.RocketService/GetRocket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocketServiceServer).GetRocket(ctx, req.(*GetRocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocketService_AddRocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocketServiceServer).AddRocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rocket.RocketService/AddRocket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocketServiceServer).AddRocket(ctx, req.(*AddRocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocketService_DeleteRocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocketServiceServer).DeleteRocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rocket.RocketService/DeleteRocket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocketServiceServer).DeleteRocket(ctx, req.(*DeleteRocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RocketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rocket.RocketService",
	HandlerType: (*RocketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRocket",
			Handler:    _RocketService_GetRocket_Handler,
		},
		{
			MethodName: "AddRocket",
			Handler:    _RocketService_AddRocket_Handler,
		},
		{
			MethodName: "DeleteRocket",
			Handler:    _RocketService_DeleteRocket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rocket/v1/rocket.proto",
}
